title: Wikipajak.org
subtitle: "A free visual guide to CSS"
description: "CSS Reference is a free visual guide to CSS. It features the most popular properties, and explains them with illustrated and animated examples."
share: "CSS Reference: a free visual guide to the most popular CSS properties."
url: https://wikipajak.org
markdown: kramdown
permalink: pretty
exclude: ["node_modules"]
port: 3000

collections:
  faq:
    output: true
    permalink: /faq/:name

defaults:
  - scope:
      path: ""
      type: "faq"
    values:
      layout: single

sass:
    style: compressed
    sass_dir: _sass